/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package chess.d_chess;

/**
 *
 * @author Yassine
 */
public class game extends javax.swing.JFrame {

    /**
     * Creates new form game
     */
    public game() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        g7 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        f5 = new javax.swing.JLabel();
        g8 = new javax.swing.JLabel();
        e8 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        c7 = new javax.swing.JLabel();
        f2 = new javax.swing.JLabel();
        c3 = new javax.swing.JLabel();
        h6 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        h3 = new javax.swing.JLabel();
        e2 = new javax.swing.JLabel();
        f4 = new javax.swing.JLabel();
        g6 = new javax.swing.JLabel();
        e1 = new javax.swing.JLabel();
        d1 = new javax.swing.JLabel();
        f7 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        e6 = new javax.swing.JLabel();
        d7 = new javax.swing.JLabel();
        d8 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        c4 = new javax.swing.JLabel();
        d4 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        h8 = new javax.swing.JLabel();
        e3 = new javax.swing.JLabel();
        g5 = new javax.swing.JLabel();
        f1 = new javax.swing.JLabel();
        e4 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        g1 = new javax.swing.JLabel();
        d5 = new javax.swing.JLabel();
        d2 = new javax.swing.JLabel();
        g4 = new javax.swing.JLabel();
        f3 = new javax.swing.JLabel();
        c5 = new javax.swing.JLabel();
        d6 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        c6 = new javax.swing.JLabel();
        g2 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        b1 = new javax.swing.JLabel();
        c8 = new javax.swing.JLabel();
        c1 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        h5 = new javax.swing.JLabel();
        d3 = new javax.swing.JLabel();
        c2 = new javax.swing.JLabel();
        h2 = new javax.swing.JLabel();
        a1 = new javax.swing.JLabel();
        h1 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        e7 = new javax.swing.JLabel();
        f8 = new javax.swing.JLabel();
        h4 = new javax.swing.JLabel();
        e5 = new javax.swing.JLabel();
        g3 = new javax.swing.JLabel();
        f6 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        h7 = new javax.swing.JLabel();
        board = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(736, 735));
        setMinimumSize(new java.awt.Dimension(736, 735));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        g7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bp.png"))); // NOI18N
        getContentPane().add(g7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 80, 80));
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 80, 80));
        getContentPane().add(f5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 80, 80));

        g8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bh.png"))); // NOI18N
        getContentPane().add(g8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 30, 80, 90));

        e8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bk.png"))); // NOI18N
        getContentPane().add(e8, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 80, 80));

        a8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bc.png"))); // NOI18N
        getContentPane().add(a8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 80, 80));

        c7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bp.png"))); // NOI18N
        getContentPane().add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 80, 80));

        f2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp.png"))); // NOI18N
        getContentPane().add(f2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 537, 80, 80));
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 80, 80));
        getContentPane().add(h6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 200, 80, 80));

        b8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bhr.png"))); // NOI18N
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 80, 80));
        getContentPane().add(h3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 80, 80));

        e2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp.png"))); // NOI18N
        getContentPane().add(e2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 537, 80, 80));
        getContentPane().add(f4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 80, 80));
        getContentPane().add(g6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 80, 80));

        e1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wk.png"))); // NOI18N
        getContentPane().add(e1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 620, 80, 80));

        d1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wq.png"))); // NOI18N
        getContentPane().add(d1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 620, 80, 80));

        f7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bp.png"))); // NOI18N
        getContentPane().add(f7, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 80, 80));

        a2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp.png"))); // NOI18N
        a2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a2MouseClicked(evt);
            }
        });
        getContentPane().add(a2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 537, 80, 80));
        getContentPane().add(e6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 80, 80));

        d7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bp.png"))); // NOI18N
        getContentPane().add(d7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 80, 80));

        d8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bq.png"))); // NOI18N
        getContentPane().add(d8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 80, 80));

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp.png"))); // NOI18N
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 537, 80, 80));
        getContentPane().add(a3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, 80, 80));
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 80, 80));
        getContentPane().add(d4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, 80, 80));
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 80, 80));

        h8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bc.png"))); // NOI18N
        getContentPane().add(h8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 80, 80));
        getContentPane().add(e3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 80, 80));
        getContentPane().add(g5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 280, 80, 80));

        f1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wb.png"))); // NOI18N
        getContentPane().add(f1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 620, 80, 80));
        getContentPane().add(e4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 80, 80));
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 80, 80));

        g1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wh.png"))); // NOI18N
        getContentPane().add(g1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 620, 80, 80));
        getContentPane().add(d5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 80, 80));

        d2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp.png"))); // NOI18N
        getContentPane().add(d2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 537, 80, 80));
        getContentPane().add(g4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 80, 80));
        getContentPane().add(f3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, 80, 80));
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 80, 80));
        getContentPane().add(d6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 80, 80));
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 80, 80));
        getContentPane().add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 80, 80));

        g2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp.png"))); // NOI18N
        getContentPane().add(g2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 537, 80, 80));
        getContentPane().add(a6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 80, 80));

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whr.png"))); // NOI18N
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 80, 80));

        c8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bb.png"))); // NOI18N
        getContentPane().add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 80, 80));

        c1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wb.png"))); // NOI18N
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 620, 80, 80));
        getContentPane().add(a4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 80, 80));
        getContentPane().add(h5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, 80, 80));
        getContentPane().add(d3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 80, 80));

        c2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp.png"))); // NOI18N
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 537, 80, 80));

        h2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wp.png"))); // NOI18N
        getContentPane().add(h2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 537, 80, 80));

        a1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wc.png"))); // NOI18N
        getContentPane().add(a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 80, 80));

        h1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wc.png"))); // NOI18N
        getContentPane().add(h1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 620, 80, 80));

        a7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bp.png"))); // NOI18N
        getContentPane().add(a7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 80, 80));
        getContentPane().add(a5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 80, 80));

        e7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bp.png"))); // NOI18N
        getContentPane().add(e7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 80, 80));

        f8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bb.png"))); // NOI18N
        getContentPane().add(f8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, 80, 80));
        getContentPane().add(h4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 370, 80, 80));
        getContentPane().add(e5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 80, 80));
        getContentPane().add(g3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 80, 80));
        getContentPane().add(f6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 80, 80));

        b7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bp.png"))); // NOI18N
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, 80));

        h7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bp.png"))); // NOI18N
        getContentPane().add(h7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 80, 80));

        board.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/board.jpg"))); // NOI18N
        getContentPane().add(board, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void a2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a2MouseClicked
        // TODO add your handling code here:
        image = a2.getIcon();
        a2.setBackground(Color.green);
    }//GEN-LAST:event_a2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new game().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a1;
    private javax.swing.JLabel a2;
    private javax.swing.JLabel a3;
    private javax.swing.JLabel a4;
    private javax.swing.JLabel a5;
    private javax.swing.JLabel a6;
    private javax.swing.JLabel a7;
    private javax.swing.JLabel a8;
    private javax.swing.JLabel b1;
    private javax.swing.JLabel b2;
    private javax.swing.JLabel b3;
    private javax.swing.JLabel b4;
    private javax.swing.JLabel b5;
    private javax.swing.JLabel b6;
    private javax.swing.JLabel b7;
    private javax.swing.JLabel b8;
    private javax.swing.JLabel board;
    private javax.swing.JLabel c1;
    private javax.swing.JLabel c2;
    private javax.swing.JLabel c3;
    private javax.swing.JLabel c4;
    private javax.swing.JLabel c5;
    private javax.swing.JLabel c6;
    private javax.swing.JLabel c7;
    private javax.swing.JLabel c8;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel d2;
    private javax.swing.JLabel d3;
    private javax.swing.JLabel d4;
    private javax.swing.JLabel d5;
    private javax.swing.JLabel d6;
    private javax.swing.JLabel d7;
    private javax.swing.JLabel d8;
    private javax.swing.JLabel e1;
    private javax.swing.JLabel e2;
    private javax.swing.JLabel e3;
    private javax.swing.JLabel e4;
    private javax.swing.JLabel e5;
    private javax.swing.JLabel e6;
    private javax.swing.JLabel e7;
    private javax.swing.JLabel e8;
    private javax.swing.JLabel f1;
    private javax.swing.JLabel f2;
    private javax.swing.JLabel f3;
    private javax.swing.JLabel f4;
    private javax.swing.JLabel f5;
    private javax.swing.JLabel f6;
    private javax.swing.JLabel f7;
    private javax.swing.JLabel f8;
    private javax.swing.JLabel g1;
    private javax.swing.JLabel g2;
    private javax.swing.JLabel g3;
    private javax.swing.JLabel g4;
    private javax.swing.JLabel g5;
    private javax.swing.JLabel g6;
    private javax.swing.JLabel g7;
    private javax.swing.JLabel g8;
    private javax.swing.JLabel h1;
    private javax.swing.JLabel h2;
    private javax.swing.JLabel h3;
    private javax.swing.JLabel h4;
    private javax.swing.JLabel h5;
    private javax.swing.JLabel h6;
    private javax.swing.JLabel h7;
    private javax.swing.JLabel h8;
    // End of variables declaration//GEN-END:variables
}
